# Cloudflared configuration for production
# Replace YOUR_TUNNEL_TOKEN with your actual token from Cloudflare

tunnel:
  token: ""

# Use latest stable version
image:
  repository: cloudflare/cloudflared
  tag: "2025.8.0"
  pullPolicy: IfNotPresent

# Production resources
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# Health checks optimized for production
livenessProbe:
  httpGet:
    path: /ready
    port: 2000
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /ready
    port: 2000
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3

# Security hardening
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL

# Node selector (optional - remove if you have only one node)
nodeSelector: {}

tolerations: []

affinity: {}
