cloudflared:
    tunnel:
        token: ENC[AES256_GCM,data:SbQ6C3ge5PtQerfk+LLjG00z0lMiGY7bd2sQAm0LwOM/GXVdQE6oGpD+zjiDMORy3cFs0JizU2K6qwEN4663XU3+4xL1wIDl16UpjlyG9Q+8t/YwNhEib/RWFvZDGstvKMfDgP+wVF9vwV/GsXHSMA4y89clqxWXkohk/sVElt4AVIoCsa4Uw1CB1uDVwcBr8dSpH9qTYelfSrLWSsKfUaW1ejP/qLnmjpAgZr8ZqlydUNPGvQx4Lw==,iv:UszWqgDE7PPSeImpoyTX5/v91R5ksKcoYo3vh0ef5Nk=,tag:62HiUsBweu8wUrPUEq1GVg==,type:str]
open-webui:
    env: []
sops:
    age:
        - recipient: age18y2mcmewrpghpurx8dt38h92pantdtxaczp9fw0dl85vrrmnx9jsm4kxda
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVmxJSnFkNEFTYjFjdHhN
            TXJEdWp0Y1NTVlMzVzBtTGJVcDRNdTBSVkc4Ck9YbUU4MWtEOHp6eGJsMUp6ZFR2
            KzEvWmR2MGRycUxFd0VtOUdSZ1dnZUUKLS0tIFl6eTQ5dmhsMm82dXNtejFZdDNa
            bzl1b2ROeG1EdUI5M1hiVUR2QlJsNmsKq13+j4Wzouum+0pA+eXx1XQo1N/BG8Lg
            ON6emgj/IdzCoZ+skAKmERGgEt6Z1DqVguG0z1KMjgAA7Y38M0IT4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T01:36:53Z"
    mac: ENC[AES256_GCM,data:wleUPH6ivUHx6xFplgkQGiGbiecZoN4l9ZyRYhyfCSR2c2p/HVWDDNDvwi+xSZxR8eNese1heQT2o9bNi4aDdT6ZksMKpQNeD+Fl+rWx1vPSyF2G+Xikw7WbwK1XecKDzMyWjJUYJM3zUiQw94KbcMY4+rl+Cm7ECHKOF/0tFqw=,iv:hDk6tYbtNlFCTK1+2KbTY7GtZpSq111hWEWhAKuy8Nk=,tag:dH7RbwJ0MFwvbM+D0lz9dg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
