apiVersion: v2
name: homarr
description: A Helm chart for Homarr - A simple, yet powerful dashboard for your server
type: application
version: 0.1.0
appVersion: "v1.33.0"

home: https://homarr.dev
sources:
  - https://github.com/homarr-labs/homarr
keywords:
  - dashboard
  - homelab
  - monitoring
maintainers:
  - name: nezdemkovski
    url: https://github.com/nezdemkovski
