{{- if .Values.sealedSecrets.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "homelab.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
spec:
  encryptedData:
    cloudflared-token: AgCaBTSylYI0tym/73qRq2FLFUj8n3oLSjIyIFitFcB2TwEsxnMTFcioIxOKX1aNV/IYCQHXUTEheZEvwjER6KYJ3TTvtTONHH8evLPCKb94jxRsj2fXmbpR68P4kHBvNAwv69vNEx4zxShEmOHFl/OEMdqopThFJS2/QfqKNsbpy357p/NERlDDriPy4vCWB/ePzGNMQn16cS58PJ2yZawDACyoNY0QGYEwkpXp6JMi2bYhzq94A4nkVMZkMAYYQHuDPKFFdYSSIDGbYDUhJ2wAULR7crtKwEMgntcsv7t2DpikIpux3lduh46ccWojbFvqhWhU1hz7ZEo0DL8ni46ecdF3Fz7EL5KavCOpiOAm3UpQ3dr804ycuNxFjfJ4Kz1H+aGoSx3fy1oMiP3d/DJC9xW6m0IBqENRJtVipbhj/FMlsIMQ1QURoSLgRmk1Z4Oa3W7QVUd4lB1EuA8N9ZGPjYaA44MLmmiLPGG8/Ug5cG/HwViQ0hSWk55hGac7ium/hz+NPnDjxjtzZ/BcgJ/57JMbKaGh9oezUuJaEe2Yprj3Rw8aO6TM0ZmiPF6u52yEulRvMnAwglvUDGskDzr7pXNW3eZOwRAcOUw5asvZ31HkRSF2aDfOn8POtRNhMbk7NDaamuHegKQ25TqASds8FXOsw180+cpRv5mgG5P4xkopUCcY24koshFy+2Ncw7sfH/oZ2DwqtvpAMT7mj9E/RHGGphbb8JTKoU6aiqtVeVD0QbRUGtgZqo+aTl9JBbK+DsHkeOuRCJYteYnyrUl6jUjlNFdLHMbTeCuuht6hkGROxDZj9AkeF3bF5E/zNVxLKeHqS2wHWlQaVYj5sa4LdyouurHVKxzmSNrRkaElde6bn9OBHGw5c1tgLsvl+w82Y8ZX4GevAGbybxIJtjxN55Efay7zoog8g7IPNqM31pMYRtuVr4Px
    open-webui-api-key: AgBiAeuIS6l45tqrj/PtliweYDeM5CRU5YgZNodnwZZRfcneljmmdj+YwRfeVbwAgU5Za6axLcSw0Er9BGGMVXSUdHAggQkEZVXZNRKBgDLXKT6R8pL0dDb2F2rYAK0lW8letuY793OlPP3H4Nx8qdjwppVacLAC6zjGsDdZgQpDD9St7FrTap4ZSf7W76bqEyGvZ/hg5MNJwuSVSscPLCJPdWRIsWamFjDW39RTxW1qwuDuzlfEeVKfxCAHg2aVpJcX4O4oBcCwrADgnX65G5V/vcCW+IgJ1AY8+l6+jOzescx90nmJzf3t0XZ/5Rv830239VN6ri5JW8S2681dWZ+O5V5g6cvrJca1c9/QF6hT0O8Lvw9f8iwArbhwTQOKAcjSjHj2bakeJPwU6qMwHOBCgQIs0a3q5A54NfLXQOuURWu0P2qsXrH49WrILq9EgAxsDzOOgfJ/ut4wte65QC/LDdUpd5IG5hKq39RtIcnnQi/xYPsaiQ0t5nPnE/BbKmG+ca5iW0rEQzUD6JTkz+np7bdpn04fGhj1kvgbbiiL6SjGN8JwqQfxx6kiZvsaa41s/rW/kwVP4t0a6aREguowvMF9iXa7N3bC/X59R/TF2r5x9M72HERl9P19g1f5oHSYnOkRUG5m8g2Fh4uBW34C3sSvYmiKf/iB1EspeenJLvVWP2J9X+eaxSAaqVYEUQ7idowRnhZsgb4YoNWz9EhLQ8uLKBi4DtECxdeuzOXufwGV1A==
  template:
    metadata:
      name: {{ include "homelab.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "homelab.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
