{{- if .Values.sealedSecrets.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "homelab.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
spec:
  encryptedData:
    cloudflared-token: AgBcV8NqC/CRJltlS/C/tS21dsQqYe88K0iaoXynCoumct/OTMp43/SRjEEPNOhaFuc3RPw/9+z8jJR0j+UF4vAmtj0q0PfLH7IoqI70YlkvLd3rN97pKd66gAZ5AsECEGTi3U7WRMBSV0lQIYS7jmKNx3viG0H6WkEaMKglvzAGTCvgVhVmSAqWsvEjEQjFlgCgTwzdixs9G7rpE/eChhKtoBZeqc9qxewAfQWqygnreLHrBtVaQNtjoBAsoRrWf1dAxmp+B/jW/X6G2TPOdzEY35W0JDMqhtau/7YmDdwlI4Hetej6eBkHJHJQq2aCy8sKROapBR4ehiRauOKXPZazfwz7n5v6zFnBNiA3pWqnAvpCJpU9Qh+5aJGnh78kXhQfiGQ4Tkr+BgrlFaVIE5xoPcq1e1x2wdnvYnh7RSzmw2jNd91PkhvvirRtrjCVKTO/XxWC4Thbi7jDQkwZfgg3UUjLy4pPtgdjLiCDIzwMSgSPXesuMjWSW7lJnItrnXL40yg8sV9Lnqp8jCUQWd//j63nYSBksnatpiVyUVzJCXSYSczZkdZ76xv5O9homuMD+BkMmVGWC3sd22syoDRVkVu/sWPHGjwzlvgDq1ZRAW3zOnXO9HWgd9GH1yu0J89BF5naYyybEDqvSeo7EAlEskQMPy76+m0xRDdc38gDnapjuOsF6r/yGJoTUqr6qd9g+UAxDWU+MiKotZjf2br0a/R78Wt3gJho2yJjnzq+FRt0+wEeX4hhx9kMP6uD+UjNfXCzY3pisO5CJW+IzLAednDuM2EUDRYhIMdCuQvauV+PkLd0H677x7JGU0Y2eStSu6tBLa7YBHdlNc+wMxBl4mgfPcHVOiLSL7UMlm9bwm+KzBPIlyxlKAH6YY28IADIZEpuJaKjweBUrx3KoBHr/ZTHIz+HuZ1TJ3PzOnkjZYEJC8vxbUlE
  template:
    metadata:
      name: {{ include "homelab.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "homelab.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
