{{- if .Values.sealedSecrets.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "homelab.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
spec:
  encryptedData:
    cloudflared-token: AgCfS/Gkq16x3cjtWUPlYlEB/R223W5BPWP6BwhpvHdQ9ArN+o26O4RbTZt6fGXuRwbYwfNqHosktMk9yVDpvDORQ3pccJfzfP+wJPZHZESmeik+ghsS7nqYpAJ48IoY3mH4Q8sN2OViDAvZ8QfbqNxyljKWg3UFQ6wFIPZu7jYNOwGgpE5lh+eCTPMpZKvN+08auhBxdILPzcufW+KHvtKQdTCB023mXfD87zZDeEv8ZqsIsETsvfSBUQsHB60sRQr9m38nzg891Flit5nDNu9FWxevHPHA7wNa2bcuvfoOw165lHs4NBx1G48iK9v3QYyeCN7aI613YOpX1EvS02T9YVqGYzJLOBMFxOsk43ujuPnrlxbe/0IFQctAe3EKmrEuT2ezvwOVR+Hh8wQjWyQNeRros0kJ2j/VXLgaaqVmnA4yt1hMyNUFh+VaeQK0m1dzYaH8oWGOdtfi5iQZJbGy4kZUv1Pmv2kdLfxm9BRrRly9B66us/DOYb2l8etpSelN9JAI6SzrwPuJlasmBXjxVvBL8A6SgAz9zrI7bXO7WPRy8Ni0pcih7Uu3pkS5D0OGLFJuoiN6peJjjXWm9edm5BAl/V3OC773AEb0ItRhBqg2KQnOtpLwBpGCxIHJtyDNRyUXp2iJ/sGAcijz1GmvuK2q4FFseq/MLvGEpd7XZ9UbuxdRP5ZqWM7lllH4aVTtKy7QU+oaLTJi4Llc5y9uaIP/95XBfCst6JPU8Dtsykk5MVHDlm/9WH+/0SQyiUFE9LhlprxRoG1uiix8ICBjJFdSozNAKEjSh2ekvoBTltETFjkXF9VjZF46Hhjwuk5gv7AOJCcMndt+N7DbspPMGqhxhLolcw0le0c6pd3Rlbwn8/PWiJ5QsgRgBekZQqgobJnTq9hbcHscNlolrRrI0sa1DPv/2jWKkd2aYcLNpOMyspkJLIfl
  template:
    metadata:
      name: {{ include "homelab.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "homelab.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
