apiVersion: v2
name: n8n
description: A Helm chart for n8n automation platform with PostgreSQL
type: application
version: 0.1.0
appVersion: "1.107.2"

home: https://n8n.io
sources:
  - https://github.com/n8n-io/n8n
keywords:
  - automation
  - workflow
  - integration
  - nocode
maintainers:
  - name: nezdemkovski
    url: https://github.com/nezdemkovski
