apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-app-of-apps
  namespace: argocd
  labels:
    app: app-of-apps
    type: bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nezdemkovski/homelab-helm-charts.git
    targetRevision: HEAD
    path: argocd
    directory:
      recurse: false
      include: "homelab-apps.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
