apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  labels:
    app: open-webui
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nezdemkovski/homelab-helm-charts.git
    targetRevision: HEAD
    path: apps/open-webui
    helm:
      valueFiles:
        - ../../environments/open-webui-values.yaml
        - ../../environments/production-secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    # Manual sync for production - require approval
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20 # Keep more history for production
